import amazonRiver from "./assets/amazon-river.jpg";
import auroraBoreale from "./assets/aurora-boreale.jpg";
import barrieraCorallina from "./assets/barriera-corallina.jpg";
import spiaggiaCaraibi from "./assets/caribbean-beach.jpg";
import cascateVictoria from "./assets/cascate-victoria.jpg"
import colosseo from "./assets/colosseo.png";
import deserto from "./assets/dune-deserto.jpg";
import fuji from "./assets/fuji.jpg";
import grandCanyon from "./assets/grand-canyon.jpg";
import machuPicchu from "./assets/machu-picchu.jpg";
import rovineGreche from "./assets/rovine-greche.jpg";
import savana from "./assets/savana-africana.jpg";
import statuaLiberta from "./assets/statua-libertà.png";
import stradeParigine from "./assets/strade-parigine.jpg";
import tajMahal from "./assets/taj-mahal.jpg";
import templiGiapponesi from "./assets/templi-giapponesi.jpg"
import tourEiffel from "./assets/tour-eiffel.png";
import venezia from "./assets/venezia.jpg";